### ISSUE TITLE
"xpartygo" does not work.

### ISSUE THREAD

**Issue by ghost** [XLabsProject/iw6x-client#495] opened 2021-10-21 08:32 UTC
Not sure if it's a bug or not, but since the console auto-completes I thought I should post.
I was trying to level up with bots.

**Comment by callme6** [comment] 2022-02-19 21:51
anyone have any issues ?

**Comment by FragsAreUs** [comment] 2022-03-11 07:13
ghost does not have ranked as of right now so xpartygo is usless as there is currently no way to level up

**Comment by diamante0018** [comment] 2022-05-08 23:26
Duplicate of #101

**Closed by diamante0018** 2022-05-08 23:26 UTC
