### ISSUE TITLE
Spawnbot at dedicated server just create bots with character captain price only

### ISSUE THREAD

**Issue by amrurikaj** [XLabsProject/iw6x-client#693] opened 2022-10-10 08:10 UTC
I don't know whether this is a problem or not but to me it's quite annoying that all bots are captain price.  :-D

**Comment by diamante0018** [comment] 2022-10-10 17:16
Not a bug worth fixing

**Comment by amrurikaj** [comment] 2022-10-10 23:27
@diamante0018 should let it open? or close it?but still annoyed with the captain price 😂

**Comment by diamante0018** [comment] 2022-10-10 23:29
Close because it's a won't fix

**Closed** 2022-10-10 23:30 UTC

**Comment by LeRutY** [comment] 2022-10-20 15:48
> Close because it's a won't fix

Bad answer, rip iw6x for people that want to level up with bots
