### ISSUE TITLE
Infected in Private Match Bugged for Friend Joining

### ISSUE THREAD

**Issue by DemonWithin115** [XLabsProject/iw6x-client#612] opened 2022-05-18 01:36 UTC
When I start up the match, everything else is fine on my end as the host, but when he joins, he's unable to choose his class, therefore is unable to play the game at all aside from being a spectator. It appears to be only the infected gamemode that gives us this bug, as all the other gamemodes still allows him to choose his class when he gets in.

**Comment by diamante0018** [comment] 2022-10-14 10:38
Would probably need to test this issue with someone else to confirm. These bugs are usually caused by game scripts or UI scripts acting up

**Comment by efinst0rm** [comment] 2022-10-23 02:10
This should be fixed here. #735

**Closed by efinst0rm** 2022-10-23 02:10 UTC
Labels: bug, important, needs info
