### ISSUE TITLE
Team Based modes bugged on Dedicated Servers?

### ISSUE THREAD

**Issue by BoxOfMysteriez** [XLabsProject/iw6x-client#827] opened 2023-01-05 18:14 UTC
While running a dedicated server, any team based mode such as tdm or snd does not display currently connected players and/or bots on the scoreboard and all players display as enemies. However, Free For All modes such as gun game, display correctly and work fine. 
Are than any specific parameters/commands that need to be set for teams to work correctly?
Gametype is being set via sv_maprotation as instructed in the server.cfg. Running client/server version 3.0.7 

![Untitled](https://user-images.githubusercontent.com/77655611/210850313-e567ffab-6a92-4fa7-8486-50e5e2cf3881.png)

**Comment by diamante0018** [comment] 2023-01-09 19:36
Can't replicate it on the experimental version of IW6x. Most likely you do not have downloaded all the iw6x client files, or you have not let the Xlabs launcher update properly.
Keep in mind this issue does not follow the template you should have read [get-help](https://github.com/XLabsProject/iw6x-client/blob/develop/.github/ISSUE_TEMPLATE/get-help.md)
The document I linked suggests to ask for these kinds of questions on the Discord server as you will not get priority if you ask here because it's not regularly monitored.
I will close this soon as the issue is invalid unless someone else can replicate it. ( I can't )

**Comment by diamante0018** [comment] 2023-01-10 20:33
Just played a game on a server I don't host and had no issues whatsoever.
I will attribute this to the OP having an incorrect install of IW6x and or forcing the server to run in private match mode instead of ranked (which should not be attempted since IW6x supports ranked matches).

**Closed by diamante0018** 2023-01-10 20:33 UTC

**Comment by efinst0rm** [comment] 2023-01-18 05:28
This is because of the missing _menu.gsc
