### ISSUE TITLE
RCON status crashes server

### ISSUE THREAD

**Issue by TheSoliderror** [XLabsProject/iw6x-client#606] opened 2022-05-07 00:03 UTC
Making a discord bot for my server I can across this, when using RCON status it will make the server crash after a minute or so, looking more into this I also found out that iw4m admin has the same issue with there plugin crashing the server due to the status command being used. It only happens when you RCON the command, when doing so in the console it works as it should with no crash. I was using the RCON status to get the player names and their guid for admin purposes, and this does work but soon after using the command on the bot or within the CMD terminal, it will crash the server. I believe it even happens when using the command in game using RCON but I personally have not tested this. I hope there is a fix for this so there can be better server management using remote tools such as Iw4m or DoktorSAS admintool script he created and I created the bot for.

**Comment by mjkzy** [comment] 2022-05-07 08:50
Would the issue be related to this?
![image](https://user-images.githubusercontent.com/64374267/167246906-21ec17c2-ffe2-45c8-a3ea-b7d279bd2127.png)

**Comment by TheSoliderror** [comment] 2022-05-07 16:31
> Would the issue be related to this?
> ![image](https://user-images.githubusercontent.com/64374267/167246906-21ec17c2-ffe2-45c8-a3ea-b7d279bd2127.png)
> 

Do you know if that was released to official release? Ik he said something about trying to fix it in the iw4m admin discord I just didn't know if he did. I can't really keep up in releases anymore sense I've been booted from the discord.

**Comment by mjkzy** [comment] 2022-05-07 16:38
Matrix confirmed that there is a fix that will be PR'd very soon.

**Comment by TheSoliderror** [comment] 2022-05-07 17:06
Okay, thank you

**Comment by diamante0018** [comment] 2022-05-07 20:37
Duplicate of #204

**Closed by diamante0018** 2022-05-07 20:37 UTC

**Comment by TheSoliderror** [comment] 2022-05-07 21:19
Sorry I didn't realize sense the name didn't mention it and that it's a year old
