### ISSUE TITLE
Frequent crashing due to imagefile error

### ISSUE THREAD

**Issue by Burvye** [XLabsProject/iw6x-client#786] opened 2022-11-24 00:11 UTC
Every time i try to launch iw6x it just stops loading on mp_character_room_heads and gives me imagefile error 0x00000006
I have tried doing the repair using the repair guide, which didn't work
I also checked my drivers using the manufacturer website but they were already up to date.
I have also searched some solutions online about tweaking settings but they don't seem to have an effect.
![image_2022-11-23_191023290](https://user-images.githubusercontent.com/110496639/203666746-e4bccf09-faf8-4a4d-b735-f4ff9fbb7310.png)

**Comment by diamante0018** [comment] 2022-11-24 00:14
Duplicate of #785 nice try

**Closed by diamante0018** 2022-11-24 00:14 UTC
