### ISSUE TITLE
after unlocking the multiplayer level up to 60 in a private game, it shows level 1

### ISSUE THREAD

**Issue by Canek-77** [XLabsProject/iw6x-client#155] opened 2020-11-03 14:03 UTC
Version 1.0.0 RC 1

**Comment by momo5502** [comment] 2020-11-03 14:07
Why do you write Version 1.0.0 RC 1?
Can you, instead, please describe the issue in detail? Where does it show level one? In the menu, in private match? When connected to a dedi? Ranking is not supported anyways, so I guess you're just refering to the fact that ranking is not working at all, which makes this issue pretty much a duplicate of #101

**Comment by momo5502** [comment] 2020-11-03 14:10
I advise you, before creating any new issues, to look if similar issues or duplicates already exist and to extend these.
And of course please properly describe the issues, don't just paste the version. We know the latest released version. It's absolutely not helpful. Like not even a tiny little bit.

**Comment by Canek-77** [comment] 2020-11-03 14:11
> Why do you write Version 1.0.0 RC 1?
> Can you, instead, please describe the issue in detail? Where does it show level one? In the menu, in private match? When connected to a dedi? Ranking is not supported anyways, so I guess you're just refering to the fact that ranking is not working at all, which makes this issue pretty much a duplicate of #101

in a private match, everywhere writes level 1, play with a friend, he also displays level 1

**Comment by Canek-77** [comment] 2020-11-03 14:13
I don't know English well, so I try to explain as best I can

**Comment by momo5502** [comment] 2020-11-03 14:17
Yes, this is expected behaviour for now. It is related to this commit: https://github.com/XLabsProject/iw6x-client/commit/9e16c6900a84f0013552e4df3354d8a94142425c
This makes this issue a duplicate of #101.

**Closed by momo5502** 2020-11-03 14:17 UTC
Labels: bug, needs info
